// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	cart "api/internal/handler/cart"
	home "api/internal/handler/home"
	order "api/internal/handler/order"
	payment "api/internal/handler/payment"
	user "api/internal/handler/user"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加商品到购物车
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: cart.AddToCartHandler(serverCtx),
			},
			{
				// 删除购物车商品
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: cart.DeleteCartHandler(serverCtx),
			},
			{
				// 获取购物车商品列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: cart.GetCartListHandler(serverCtx),
			},
			{
				// 更新购物车商品数量
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: cart.UpdateCartHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/cart"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 首页Banner
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: home.HomeBannerHandler(serverCtx),
			},
			{
				// 分类商品列表
				Method:  http.MethodGet,
				Path:    "/category/products",
				Handler: home.HomeCategoryProductsHandler(serverCtx),
			},
			{
				// 首页抢购
				Method:  http.MethodGet,
				Path:    "/flashsale",
				Handler: home.HomeFlashSaleHandler(serverCtx),
			},
			{
				// 商品评价
				Method:  http.MethodGet,
				Path:    "/product/comments",
				Handler: home.HomeProductCommentsHandler(serverCtx),
			},
			{
				// 商品详情
				Method:  http.MethodGet,
				Path:    "/product/detail",
				Handler: home.HomeProductDetailHandler(serverCtx),
			},
			{
				// 首页推荐商品
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: home.HomeRecommendProductsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 获取订单详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: order.OrderDetailHandler(serverCtx),
			},
			{
				// 获取用户订单列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: order.UserOrderListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 支付回调通知
				Method:  http.MethodPost,
				Path:    "/callback",
				Handler: payment.PaymentCallbackHandler(serverCtx),
			},
			{
				// 发起支付
				Method:  http.MethodPost,
				Path:    "/pay",
				Handler: payment.InitiatePaymentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/payment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				// 用户注销
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: user.UserLogoutHandler(serverCtx),
			},
			{
				// 更新用户信息
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: user.UserUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/user"),
	)
}
