// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddToCartReq struct {
	ProductID int64 `json:"product_id"`         // 商品ID
	Quantity  int64 `json:"quantity,default:1"` // 商品数量
}

type AddToCartResp struct {
	Success bool `json:"success"` // 是否添加成功
}

type Address struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`    // 用户ID
	Recipient string `json:"recipient"`  // 收件人姓名
	Phone     string `json:"phone"`      // 收件人电话
	Province  string `json:"province"`   // 省份
	City      string `json:"city"`       // 城市
	District  string `json:"district"`   // 区/县
	Detail    string `json:"detail"`     // 详细地址
	IsDefault bool   `json:"is_default"` // 是否默认地址
	CreatedAt int64  `json:"created_at"` // 创建时间
	UpdatedAt int64  `json:"updated_at"` // 更新时间
}

type Banner struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`        // Banner名称
	BannerImage Image  `json:"image"`       // Banner图片
	LinkURL     string `json:"link_url"`    // 点击跳转地址
	Description string `json:"description"` // Banner描述
}

type CartItem struct {
	ID        int64   `json:"id"`         // 购物车项ID
	Product   Product `json:"product"`    // 商品信息
	Quantity  int64   `json:"quantity"`   // 商品数量
	AddedAt   int64   `json:"added_at"`   // 添加时间
	UpdatedAt int64   `json:"updated_at"` // 更新时间
}

type CartListResp struct {
	Items []*CartItem `json:"items"` // 购物车商品列表
}

type CategoryProductsReq struct {
	Category string `json:"category"` // 商品分类
	Cursor   int64  `json:"cursor"`   // 分页游标
	Limit    int64  `json:"limit"`    // 每页数量
	SortBy   string `json:"sort_by"`  // 排序字段，如：price、created_at
}

type CategoryProductsResp struct {
	Products []*Product `json:"products"` // 分类商品列表
	IsEnd    bool       `json:"is_end"`   // 是否最后一页
	LastVal  int64      `json:"last_val"` // 数据创建时间(作为下标，实际对应商品的CreatedAt字段)
}

type Comment struct {
	ID            int64   `json:"id"`
	ProductID     int64   `json:"product_id"`     // 商品ID
	UserID        int64   `json:"user_id"`        // 用户ID
	Rating        int64   `json:"rating"`         // 评分，1-5
	Content       string  `json:"content"`        // 评论内容
	CreatedAt     int64   `json:"created_at"`     // 创建时间
	CommentImages []Image `json:"comment_images"` // 评论图片
}

type CommentListReq struct {
	ProductID int64 `json:"product_id"` // 商品ID
	Cursor    int64 `json:"cursor"`     // 分页游标
	Limit     int64 `json:"limit"`      // 每页数量
}

type CommentListResp struct {
	Comments []*Comment `json:"comments"` // 评论详情
	IsEnd    bool       `json:"is_end"`   // 是否最后一页
	LastVal  int64      `json:"last_val"` // 数据创建时间(作为下标，实际对应评论的CreatedAt字段)
}

type CreateOrderReq struct {
	UserID        int64  `json:"user_id"`        // 用户ID
	ProductID     int64  `json:"product_id"`     // 商品ID
	Quantity      int64  `json:"quantity"`       // 购买数量
	AddressID     int64  `json:"address_id"`     // 收货地址ID
	PaymentMethod string `json:"payment_method"` // 支付方式
}

type CreateOrderResp struct {
	OrderID string `json:"order_id"` // 创建的订单ID
}

type DeleteCartReq struct {
	CartItemID int64 `json:"cart_item_id"` // 购物车项ID
}

type DeleteCartResp struct {
	Success bool `json:"success"` // 是否删除成功
}

type FlashSaleResp struct {
	StartTime int64      `json:"start_time"` // 抢购开始时间
	Products  []*Product `json:"products"`   // 商品列表
}

type HomeBannerResp struct {
	Banners []*Banner `json:"banners"`
}

type Image struct {
	ID  int64  `json:"id"`  // 图片ID
	URL string `json:"url"` // 图片地址
}

type InitiatePaymentReq struct {
	OrderID     string `json:"order_id"`     // 订单号
	ServiceType string `json:"service_type"` // 服务类型
}

type InitiatePaymentResp struct {
	Appid     string `json:"app_id"` //应用ID
	NonceStr  string `json:"nonce_str"`
	PaySign   string `json:"pay_sign"`
	Package   string `json:"package"`
	Timestamp string `json:"timestamp"`
	SignType  string `json:"sign_type"`
}

type Order struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`     // 用户ID
	ProductID  int64   `json:"product_id"`  // 商品ID
	AddressID  int64   `json:"address_id"`  // 收货地址ID
	Quantity   int64   `json:"quantity"`    // 购买数量
	Payment    float64 `json:"payment"`     // 付款金额
	PostCost   float64 `json:"post_cost"`   // 邮费
	TotalPrice float64 `json:"total_price"` // 总价
	Status     int64   `json:"status"`      // 订单状态，如：1-已支付、0-未支付
	CreatedAt  int64   `json:"created_at"`  // 创建时间
	UpdatedAt  int64   `json:"updated_at"`  // 更新时间
}

type OrderDetailReq struct {
	OrderID string `json:"order_id"` // 订单ID
}

type OrderDetailResp struct {
	OrderInfo Order `json:"order_info"` // 订单详情
}

type PaymentCallbackReq struct {
}

type PaymentCallbackResp struct {
	ReturnCode string `json:"return_code"` // 返回状态码
}

type Product struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`        // 商品名称
	Images      []Image `json:"images"`      // 商品图片
	Price       float64 `json:"price"`       // 商品价格
	Stock       int64   `json:"stock"`       // 商品库存
	Category    string  `json:"category"`    // 商品分类
	Status      int64   `json:"status"`      // 商品状态，如：1-正常、0-下架
	Description string  `json:"description"` // 商品描述
	CreatedAt   int64   `json:"created_at"`  // 创建时间
	UpdatedAt   int64   `json:"updated_at"`  // 更新时间
}

type ProductDetailReq struct {
	ProductID int64 `json:"product_id"` // 商品ID
}

type ProductDetailResp struct {
	Product *Product `json:"product"` // 商品详情
}

type RecommendProductsReq struct {
	Cursor int64 `json:"cursor"` // 分页游标
	Limit  int64 `json:"limit"`  // 每页数量
}

type RecommendProductsResp struct {
	Products []*Product `json:"products"` // 推荐商品列表
	IsEnd    bool       `json:"is_end"`   // 是否最后一页
	LastVal  int64      `json:"last_val"` // 数据创建时间(作为下标，实际对应商品的CreatedAt字段)
}

type UpdateCartReq struct {
	CartItemID int64 `json:"cart_item_id"` // 购物车项ID
	Quantity   int64 `json:"quantity"`     // 新的商品数量
}

type UpdateCartResp struct {
	Success bool `json:"success"` // 是否更新成功
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`   // 用户名
	Nickname  string `json:"nickname"`   // 昵称
	Avatar    Image  `json:"avatar"`     // 用户头像
	Phone     string `json:"phone"`      // 手机号
	Email     string `json:"email"`      // 邮箱
	Password  string `json:"password"`   // 密码（加密存储）
	CreatedAt int64  `json:"created_at"` // 创建时间
	UpdatedAt int64  `json:"updated_at"` // 更新时间
}

type UserInfoResp struct {
	UserInfo User `json:"user_info"` // 用户信息
}

type UserLoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type UserLoginResp struct {
	AccessToken  string `json:"access_token"`  // 登录成功后返回的JWT令牌
	AccessExpire int64  `json:"access_expire"` // 访问令牌过期时间，单位秒
	UserID       int64  `json:"user_id"`       // 登录成功的用户ID
	Nickname     string `json:"nickname"`      // 用户昵称
}

type UserLogoutResp struct {
	Success bool `json:"success"` // 是否注销成功
}

type UserOrderListReq struct {
	UserID int64 `json:"user_id"` // 用户ID
	Cursor int64 `json:"cursor"`  // 游标
	Limit  int64 `json:"limit"`   // 每页数量
}

type UserOrderListResp struct {
	Orders  []Order `json:"orders"`   // 订单列表
	IsEnd   bool    `json:"is_end"`   // 是否最后一页
	LastVal int64   `json:"last_val"` // 数据创建时间(作为下标，实际对应订单的CreatedAt字段)
}

type UserRegisterReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
	Phone    string `json:"phone"`    // 手机号
}

type UserRegisterResp struct {
	Success      bool   `json:"success"`       // 注册成功标志
	UserID       int64  `json:"user_id"`       // 新注册用户的ID
	AccessToken  string `json:"access_token"`  // 注册成功后返回的访问令牌
	AccessExpire int64  `json:"access_expire"` // 访问令牌过期时间，单位秒
}

type UserUpdateReq struct {
	UserID   int64  `json:"user_id"`  // 用户ID
	Username string `json:"username"` // 用户名
	Avatar   Image  `json:"avatar"`   // 用户头像
	Phone    string `json:"phone"`    // 手机号
}

type UserUpdateResp struct {
	Success bool `json:"success"` // 是否更新成功
}
