// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bannerFieldNames          = builder.RawFieldNames(&Banner{})
	bannerRows                = strings.Join(bannerFieldNames, ",")
	bannerRowsExpectAutoSet   = strings.Join(stringx.Remove(bannerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bannerRowsWithPlaceHolder = strings.Join(stringx.Remove(bannerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductBannerIdPrefix = "cache:product:banner:id:"
)

type (
	bannerModel interface {
		Insert(ctx context.Context, data *Banner) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Banner, error)
		Update(ctx context.Context, data *Banner) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultBannerModel struct {
		sqlc.CachedConn
		table string
	}

	Banner struct {
		Id          uint64    `db:"id"`          // 轮播图id
		Name        string    `db:"name"`        // 轮播图名称
		ImageId     uint64    `db:"image_id"`    // 图片id
		LinkUrl     string    `db:"link_url"`    // 链接地址
		Description string    `db:"description"` // 轮播图描述
		Status      int64     `db:"status"`      // 状态1-显示 2-隐藏
		CreateAt    time.Time `db:"create_at"`   // 创建时间
		UpdateAt    time.Time `db:"update_at"`   // 更新时间
	}
)

func newBannerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBannerModel {
	return &defaultBannerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`banner`",
	}
}

func (m *defaultBannerModel) Delete(ctx context.Context, id uint64) error {
	productBannerIdKey := fmt.Sprintf("%s%v", cacheProductBannerIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, productBannerIdKey)
	return err
}

func (m *defaultBannerModel) FindOne(ctx context.Context, id uint64) (*Banner, error) {
	productBannerIdKey := fmt.Sprintf("%s%v", cacheProductBannerIdPrefix, id)
	var resp Banner
	err := m.QueryRowCtx(ctx, &resp, productBannerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bannerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBannerModel) Insert(ctx context.Context, data *Banner) (sql.Result, error) {
	productBannerIdKey := fmt.Sprintf("%s%v", cacheProductBannerIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, bannerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.ImageId, data.LinkUrl, data.Description, data.Status)
	}, productBannerIdKey)
	return ret, err
}

func (m *defaultBannerModel) Update(ctx context.Context, data *Banner) error {
	productBannerIdKey := fmt.Sprintf("%s%v", cacheProductBannerIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bannerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.ImageId, data.LinkUrl, data.Description, data.Status, data.Id)
	}, productBannerIdKey)
	return err
}

func (m *defaultBannerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductBannerIdPrefix, primary)
}

func (m *defaultBannerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bannerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBannerModel) tableName() string {
	return m.table
}
