// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imageFieldNames          = builder.RawFieldNames(&Image{})
	imageRows                = strings.Join(imageFieldNames, ",")
	imageRowsExpectAutoSet   = strings.Join(stringx.Remove(imageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imageRowsWithPlaceHolder = strings.Join(stringx.Remove(imageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductImageIdPrefix = "cache:product:image:id:"
)

type (
	imageModel interface {
		Insert(ctx context.Context, data *Image) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Image, error)
		Update(ctx context.Context, data *Image) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultImageModel struct {
		sqlc.CachedConn
		table string
	}

	Image struct {
		Id        uint64    `db:"id"`         // 图片id
		ProductId uint64    `db:"product_id"` // 商品Id
		Url       string    `db:"url"`        // 图片地址
		Type      int64     `db:"type"`       // 图片类型1-单图 2-详情图
		CreateAt  time.Time `db:"create_at"`  // 创建时间
		UpdateAt  time.Time `db:"update_at"`  // 更新时间
	}
)

func newImageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImageModel {
	return &defaultImageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`image`",
	}
}

func (m *defaultImageModel) Delete(ctx context.Context, id uint64) error {
	productImageIdKey := fmt.Sprintf("%s%v", cacheProductImageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, productImageIdKey)
	return err
}

func (m *defaultImageModel) FindOne(ctx context.Context, id uint64) (*Image, error) {
	productImageIdKey := fmt.Sprintf("%s%v", cacheProductImageIdPrefix, id)
	var resp Image
	err := m.QueryRowCtx(ctx, &resp, productImageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImageModel) Insert(ctx context.Context, data *Image) (sql.Result, error) {
	productImageIdKey := fmt.Sprintf("%s%v", cacheProductImageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, imageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Url, data.Type)
	}, productImageIdKey)
	return ret, err
}

func (m *defaultImageModel) Update(ctx context.Context, data *Image) error {
	productImageIdKey := fmt.Sprintf("%s%v", cacheProductImageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProductId, data.Url, data.Type, data.Id)
	}, productImageIdKey)
	return err
}

func (m *defaultImageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductImageIdPrefix, primary)
}

func (m *defaultImageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImageModel) tableName() string {
	return m.table
}
