// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productCategoryFieldNames          = builder.RawFieldNames(&ProductCategory{})
	productCategoryRows                = strings.Join(productCategoryFieldNames, ",")
	productCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(productCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(productCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductProductCategoryIdPrefix = "cache:product:productCategory:id:"
)

type (
	productCategoryModel interface {
		Insert(ctx context.Context, data *ProductCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProductCategory, error)
		Update(ctx context.Context, data *ProductCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	ProductCategory struct {
		Id       uint64    `db:"id"`        // 分类id
		ParentId int64     `db:"parent_id"` // 父类别id当id=0时说明是根节点,一级类别
		Name     string    `db:"name"`      // 类别名称
		Status   int64     `db:"status"`    // 类别状态1-正常,2-已废弃
		CreateAt time.Time `db:"create_at"` // 创建时间
		UpdateAt time.Time `db:"update_at"` // 更新时间
	}
)

func newProductCategoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductCategoryModel {
	return &defaultProductCategoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product_category`",
	}
}

func (m *defaultProductCategoryModel) Delete(ctx context.Context, id uint64) error {
	productProductCategoryIdKey := fmt.Sprintf("%s%v", cacheProductProductCategoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, productProductCategoryIdKey)
	return err
}

func (m *defaultProductCategoryModel) FindOne(ctx context.Context, id uint64) (*ProductCategory, error) {
	productProductCategoryIdKey := fmt.Sprintf("%s%v", cacheProductProductCategoryIdPrefix, id)
	var resp ProductCategory
	err := m.QueryRowCtx(ctx, &resp, productProductCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productCategoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductCategoryModel) Insert(ctx context.Context, data *ProductCategory) (sql.Result, error) {
	productProductCategoryIdKey := fmt.Sprintf("%s%v", cacheProductProductCategoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, productCategoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.Status)
	}, productProductCategoryIdKey)
	return ret, err
}

func (m *defaultProductCategoryModel) Update(ctx context.Context, data *ProductCategory) error {
	productProductCategoryIdKey := fmt.Sprintf("%s%v", cacheProductProductCategoryIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productCategoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.Status, data.Id)
	}, productProductCategoryIdKey)
	return err
}

func (m *defaultProductCategoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductProductCategoryIdPrefix, primary)
}

func (m *defaultProductCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productCategoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductCategoryModel) tableName() string {
	return m.table
}
