// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package productclient

import (
	"context"

	"product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Banner                      = product.Banner
	BannerRequest               = product.BannerRequest
	BannerResponse              = product.BannerResponse
	CheckAndUpdateStockRequest  = product.CheckAndUpdateStockRequest
	CheckAndUpdateStockResponse = product.CheckAndUpdateStockResponse
	DecrStockRequest            = product.DecrStockRequest
	DecrStockResponse           = product.DecrStockResponse
	Image                       = product.Image
	ProductItem                 = product.ProductItem
	ProductItemRequest          = product.ProductItemRequest
	ProductsByCategoryRequest   = product.ProductsByCategoryRequest
	ProductsByCategoryResponse  = product.ProductsByCategoryResponse
	ProductsRequest             = product.ProductsRequest
	ProductsResponse            = product.ProductsResponse
	UpdateProductStockRequest   = product.UpdateProductStockRequest
	UpdateProductStockResponse  = product.UpdateProductStockResponse

	Product interface {
		Product(ctx context.Context, in *ProductItemRequest, opts ...grpc.CallOption) (*ProductItem, error)
		ProductsByIds(ctx context.Context, in *ProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
		ProductsByCategory(ctx context.Context, in *ProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductsByCategoryResponse, error)
		UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error)
		CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockRequest, opts ...grpc.CallOption) (*CheckAndUpdateStockResponse, error)
		CheckProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error)
		RollbackProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error)
		DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error)
		DecrStockRevert(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error)
		GetBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) Product(ctx context.Context, in *ProductItemRequest, opts ...grpc.CallOption) (*ProductItem, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Product(ctx, in, opts...)
}

func (m *defaultProduct) ProductsByIds(ctx context.Context, in *ProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ProductsByIds(ctx, in, opts...)
}

func (m *defaultProduct) ProductsByCategory(ctx context.Context, in *ProductsByCategoryRequest, opts ...grpc.CallOption) (*ProductsByCategoryResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ProductsByCategory(ctx, in, opts...)
}

func (m *defaultProduct) UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateProductStock(ctx, in, opts...)
}

func (m *defaultProduct) CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockRequest, opts ...grpc.CallOption) (*CheckAndUpdateStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CheckAndUpdateStock(ctx, in, opts...)
}

func (m *defaultProduct) CheckProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CheckProductStock(ctx, in, opts...)
}

func (m *defaultProduct) RollbackProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.RollbackProductStock(ctx, in, opts...)
}

func (m *defaultProduct) DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DecrStock(ctx, in, opts...)
}

func (m *defaultProduct) DecrStockRevert(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*DecrStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DecrStockRevert(ctx, in, opts...)
}

func (m *defaultProduct) GetBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetBanner(ctx, in, opts...)
}
