// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images        []*Image               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductItem) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductItem) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProductItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ProductItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItemRequest) Reset() {
	*x = ProductItemRequest{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItemRequest) ProtoMessage() {}

func (x *ProductItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItemRequest.ProtoReflect.Descriptor instead.
func (*ProductItemRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsRequest) Reset() {
	*x = ProductsRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsRequest) ProtoMessage() {}

func (x *ProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsRequest.ProtoReflect.Descriptor instead.
func (*ProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductsRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      map[int64]*ProductItem `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsResponse) Reset() {
	*x = ProductsResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResponse) ProtoMessage() {}

func (x *ProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResponse.ProtoReflect.Descriptor instead.
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductsResponse) GetProducts() map[int64]*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Ps            int32                  `protobuf:"varint,3,opt,name=ps,proto3" json:"ps,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsByCategoryRequest) Reset() {
	*x = ProductsByCategoryRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsByCategoryRequest) ProtoMessage() {}

func (x *ProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductsByCategoryRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductsByCategoryRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ProductsByCategoryRequest) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *ProductsByCategoryRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductsByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnd         bool                   `protobuf:"varint,1,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Products      []*ProductItem         `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsByCategoryResponse) Reset() {
	*x = ProductsByCategoryResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsByCategoryResponse) ProtoMessage() {}

func (x *ProductsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*ProductsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductsByCategoryResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *ProductsByCategoryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProductsByCategoryResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductsByCategoryResponse) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockRequest) Reset() {
	*x = UpdateProductStockRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockRequest) ProtoMessage() {}

func (x *UpdateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductStockRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockResponse) Reset() {
	*x = UpdateProductStockResponse{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockResponse) ProtoMessage() {}

func (x *UpdateProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

type CheckAndUpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndUpdateStockRequest) Reset() {
	*x = CheckAndUpdateStockRequest{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndUpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndUpdateStockRequest) ProtoMessage() {}

func (x *CheckAndUpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndUpdateStockRequest.ProtoReflect.Descriptor instead.
func (*CheckAndUpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAndUpdateStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckAndUpdateStockRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type CheckAndUpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndUpdateStockResponse) Reset() {
	*x = CheckAndUpdateStockResponse{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndUpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndUpdateStockResponse) ProtoMessage() {}

func (x *CheckAndUpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndUpdateStockResponse.ProtoReflect.Descriptor instead.
func (*CheckAndUpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

type DecrStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockRequest) Reset() {
	*x = DecrStockRequest{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockRequest) ProtoMessage() {}

func (x *DecrStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockRequest.ProtoReflect.Descriptor instead.
func (*DecrStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *DecrStockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecrStockRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DecrStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockResponse) Reset() {
	*x = DecrStockResponse{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockResponse) ProtoMessage() {}

func (x *DecrStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockResponse.ProtoReflect.Descriptor instead.
func (*DecrStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images        *Image                 `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	LinkUrl       string                 `protobuf:"bytes,4,opt,name=linkUrl,proto3" json:"linkUrl,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *Banner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Banner) GetImages() *Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Banner) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *BannerResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\")\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x99\x02\n" +
	"\vProductItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x06images\x18\x03 \x03(\v2\x0e.product.ImageR\x06images\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"3\n" +
	"\x12ProductItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"2\n" +
	"\x0fProductsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\"\xaa\x01\n" +
	"\x10ProductsResponse\x12C\n" +
	"\bproducts\x18\x01 \x03(\v2'.product.ProductsResponse.ProductsEntryR\bproducts\x1aQ\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.product.ProductItemR\x05value:\x028\x01\"\x83\x01\n" +
	"\x19ProductsByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x0e\n" +
	"\x02ps\x18\x03 \x01(\x05R\x02ps\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\"\xa2\x01\n" +
	"\x1aProductsByCategoryResponse\x12\x15\n" +
	"\x06is_end\x18\x01 \x01(\bR\x05isEnd\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x120\n" +
	"\bproducts\x18\x04 \x03(\v2\x14.product.ProductItemR\bproducts\"L\n" +
	"\x19UpdateProductStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x1c\n" +
	"\x1aUpdateProductStockResponse\"M\n" +
	"\x1aCheckAndUpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x1d\n" +
	"\x1bCheckAndUpdateStockResponse\"4\n" +
	"\x10DecrStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x13\n" +
	"\x11DecrStockResponse\"\x90\x01\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x06images\x18\x03 \x01(\v2\x0e.product.ImageR\x06images\x12\x18\n" +
	"\alinkUrl\x18\x04 \x01(\tR\alinkUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x0f\n" +
	"\rBannerRequest\";\n" +
	"\x0eBannerResponse\x12)\n" +
	"\abanners\x18\x01 \x03(\v2\x0f.product.BannerR\abanners2\xb8\x06\n" +
	"\aProduct\x12<\n" +
	"\aProduct\x12\x1b.product.ProductItemRequest\x1a\x14.product.ProductItem\x12D\n" +
	"\rProductsByIds\x12\x18.product.ProductsRequest\x1a\x19.product.ProductsResponse\x12]\n" +
	"\x12ProductsByCategory\x12\".product.ProductsByCategoryRequest\x1a#.product.ProductsByCategoryResponse\x12]\n" +
	"\x12UpdateProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12`\n" +
	"\x13CheckAndUpdateStock\x12#.product.CheckAndUpdateStockRequest\x1a$.product.CheckAndUpdateStockResponse\x12\\\n" +
	"\x11CheckProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12_\n" +
	"\x14RollbackProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12B\n" +
	"\tDecrStock\x12\x19.product.DecrStockRequest\x1a\x1a.product.DecrStockResponse\x12H\n" +
	"\x0fDecrStockRevert\x12\x19.product.DecrStockRequest\x1a\x1a.product.DecrStockResponse\x12<\n" +
	"\tGetBanner\x12\x16.product.BannerRequest\x1a\x17.product.BannerResponseB\vZ\t./productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_product_proto_goTypes = []any{
	(*Image)(nil),                       // 0: product.Image
	(*ProductItem)(nil),                 // 1: product.ProductItem
	(*ProductItemRequest)(nil),          // 2: product.ProductItemRequest
	(*ProductsRequest)(nil),             // 3: product.ProductsRequest
	(*ProductsResponse)(nil),            // 4: product.ProductsResponse
	(*ProductsByCategoryRequest)(nil),   // 5: product.ProductsByCategoryRequest
	(*ProductsByCategoryResponse)(nil),  // 6: product.ProductsByCategoryResponse
	(*UpdateProductStockRequest)(nil),   // 7: product.UpdateProductStockRequest
	(*UpdateProductStockResponse)(nil),  // 8: product.UpdateProductStockResponse
	(*CheckAndUpdateStockRequest)(nil),  // 9: product.CheckAndUpdateStockRequest
	(*CheckAndUpdateStockResponse)(nil), // 10: product.CheckAndUpdateStockResponse
	(*DecrStockRequest)(nil),            // 11: product.DecrStockRequest
	(*DecrStockResponse)(nil),           // 12: product.DecrStockResponse
	(*Banner)(nil),                      // 13: product.Banner
	(*BannerRequest)(nil),               // 14: product.BannerRequest
	(*BannerResponse)(nil),              // 15: product.BannerResponse
	nil,                                 // 16: product.ProductsResponse.ProductsEntry
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: product.ProductItem.images:type_name -> product.Image
	16, // 1: product.ProductsResponse.products:type_name -> product.ProductsResponse.ProductsEntry
	1,  // 2: product.ProductsByCategoryResponse.products:type_name -> product.ProductItem
	0,  // 3: product.Banner.images:type_name -> product.Image
	13, // 4: product.BannerResponse.banners:type_name -> product.Banner
	1,  // 5: product.ProductsResponse.ProductsEntry.value:type_name -> product.ProductItem
	2,  // 6: product.Product.Product:input_type -> product.ProductItemRequest
	3,  // 7: product.Product.ProductsByIds:input_type -> product.ProductsRequest
	5,  // 8: product.Product.ProductsByCategory:input_type -> product.ProductsByCategoryRequest
	7,  // 9: product.Product.UpdateProductStock:input_type -> product.UpdateProductStockRequest
	9,  // 10: product.Product.CheckAndUpdateStock:input_type -> product.CheckAndUpdateStockRequest
	7,  // 11: product.Product.CheckProductStock:input_type -> product.UpdateProductStockRequest
	7,  // 12: product.Product.RollbackProductStock:input_type -> product.UpdateProductStockRequest
	11, // 13: product.Product.DecrStock:input_type -> product.DecrStockRequest
	11, // 14: product.Product.DecrStockRevert:input_type -> product.DecrStockRequest
	14, // 15: product.Product.GetBanner:input_type -> product.BannerRequest
	1,  // 16: product.Product.Product:output_type -> product.ProductItem
	4,  // 17: product.Product.ProductsByIds:output_type -> product.ProductsResponse
	6,  // 18: product.Product.ProductsByCategory:output_type -> product.ProductsByCategoryResponse
	8,  // 19: product.Product.UpdateProductStock:output_type -> product.UpdateProductStockResponse
	10, // 20: product.Product.CheckAndUpdateStock:output_type -> product.CheckAndUpdateStockResponse
	8,  // 21: product.Product.CheckProductStock:output_type -> product.UpdateProductStockResponse
	8,  // 22: product.Product.RollbackProductStock:output_type -> product.UpdateProductStockResponse
	12, // 23: product.Product.DecrStock:output_type -> product.DecrStockResponse
	12, // 24: product.Product.DecrStockRevert:output_type -> product.DecrStockResponse
	15, // 25: product.Product.GetBanner:output_type -> product.BannerResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
