// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"

	"product/rpc/internal/logic"
	"product/rpc/internal/svc"
	"product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Product(ctx context.Context, in *product.ProductItemRequest) (*product.ProductItem, error) {
	l := logic.NewProductLogic(ctx, s.svcCtx)
	return l.Product(in)
}

func (s *ProductServer) ProductsByIds(ctx context.Context, in *product.ProductsRequest) (*product.ProductsResponse, error) {
	l := logic.NewProductsByIdsLogic(ctx, s.svcCtx)
	return l.ProductsByIds(in)
}

func (s *ProductServer) ProductsByCategory(ctx context.Context, in *product.ProductsByCategoryRequest) (*product.ProductsByCategoryResponse, error) {
	l := logic.NewProductsByCategoryLogic(ctx, s.svcCtx)
	return l.ProductsByCategory(in)
}

func (s *ProductServer) UpdateProductStock(ctx context.Context, in *product.UpdateProductStockRequest) (*product.UpdateProductStockResponse, error) {
	l := logic.NewUpdateProductStockLogic(ctx, s.svcCtx)
	return l.UpdateProductStock(in)
}

func (s *ProductServer) CheckAndUpdateStock(ctx context.Context, in *product.CheckAndUpdateStockRequest) (*product.CheckAndUpdateStockResponse, error) {
	l := logic.NewCheckAndUpdateStockLogic(ctx, s.svcCtx)
	return l.CheckAndUpdateStock(in)
}

func (s *ProductServer) CheckProductStock(ctx context.Context, in *product.UpdateProductStockRequest) (*product.UpdateProductStockResponse, error) {
	l := logic.NewCheckProductStockLogic(ctx, s.svcCtx)
	return l.CheckProductStock(in)
}

func (s *ProductServer) RollbackProductStock(ctx context.Context, in *product.UpdateProductStockRequest) (*product.UpdateProductStockResponse, error) {
	l := logic.NewRollbackProductStockLogic(ctx, s.svcCtx)
	return l.RollbackProductStock(in)
}

func (s *ProductServer) DecrStock(ctx context.Context, in *product.DecrStockRequest) (*product.DecrStockResponse, error) {
	l := logic.NewDecrStockLogic(ctx, s.svcCtx)
	return l.DecrStock(in)
}

func (s *ProductServer) DecrStockRevert(ctx context.Context, in *product.DecrStockRequest) (*product.DecrStockResponse, error) {
	l := logic.NewDecrStockRevertLogic(ctx, s.svcCtx)
	return l.DecrStockRevert(in)
}

func (s *ProductServer) GetBanner(ctx context.Context, in *product.BannerRequest) (*product.BannerResponse, error) {
	l := logic.NewGetBannerLogic(ctx, s.svcCtx)
	return l.GetBanner(in)
}
